### ISSUE TITLE
[bug] pre-commit fails

### ISSUE THREAD

**Issue by TFK70** [Atlantis-Lab/actl#103]
### Описание бага
1. **@atlantis-lab/precommit@latest**
2. Прекоммит фейлится с ошибкой
   
### Воспроизведение
Шаги для воспроизведения бага:
1. Заводим репозиторий или идем в существующий
2. Пытаемся сделать коммит редактируя коммит месседж
3. Видим оишбку

### Ожидаемое поведение
Прекоммит должен корректно выполнять все степы без ошибок

### Материалы
```javascript
husky > pre-commit (node v14.14.0)
  ↓ Stashing changes... [skipped]
    → No partially staged files found...
  ✔️ Running tasks...
husky > commit-msg (node v14.14.0)
/Users/torinasakura/workspace/aeterna/web/node_modules/@commitlint/cli/lib/cli.js:124
        throw err;
        ^

[Error: ENOENT: no such file or directory, open '/Users/torinasakura/workspace/aeterna/web/[object Object]'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/torinasakura/workspace/aeterna/web/[object Object]'
}

husky > commit-msg hook failed (add --no-verify to bypass)
/Users/torinasakura/workspace/aeterna/web/node_modules/commitizen/dist/cli/strategies/git-cz.js:85
        throw error;
        ^

Error: git exited with error code 1
    at ChildProcess.<anonymous> (/Users/torinasakura/workspace/aeterna/web/node_modules/commitizen/dist/git/commit.js:807:28)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12) {
  code: 1,
  signal: null
}
error Command failed with exit code 1.
```
### Данные окружения
 - Ubuntu@20.04
 - Chrome Version 88.0.4324.182 (Official Build) (64-bit)

**Comment by themetronome** [comment]
### Описание бага
При коммите с использованием actl, прекоммит хук **actl commitmsg** падает с ошибкой

### Воспроизведение
Шаги для воспроизведения бага:

1. Заводим репозиторий или идем в существующий
2. Используем yarn скрипт - **actl commit** для коммита (также **actl commit** запускался и глобально и локально без yarn)
3. Заполняем все поля предлагаемые визардом
4. На этапе отработки husky - видим ошибку

### Ожидаемое поведение
Измененные файлы должны успешно закоммититься

### Материалы
Сама ошибка
```javascript
husky > pre-commit (node v14.16.0)
  ↓ Stashing changes... [skipped]
    → No partially staged files found...
  ✔ Running tasks...
husky > commit-msg (node v14.16.0)
/home/themetronome/repos/frontend-study-themetronome/node_modules/@commitlint/cli/lib/cli.js:100
        throw err;
        ^

[Error: ENOENT: no such file or directory, open '/home/themetronome/repos/frontend-study-themetronome/[object Object]'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/themetronome/repos/frontend-study-themetronome/[object Object]'
}

husky > commit-msg hook failed (add --no-verify to bypass)
/home/themetronome/.config/yarn/global/node_modules/commitizen/dist/cli/strategies/git-cz.js:85
        throw error;
        ^

Error: git exited with error code 1
    at ChildProcess.<anonymous> (/home/themetronome/.config/yarn/global/node_modules/commitizen/dist/git/commit.js:807:28)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12) {
  code: 1,
  signal: null
}
```
также, если убрать совсем хуки - коммитится успешно, если оставить только **actl precommit** - тоже коммитится успешно

### Данные окружения

- OS: Ubuntu 20.04.2 LTS x86_64
- Node: v14.16.0
- Yarn: 1.22.5
- actl: 0.4.27

package.json
```javascript
{
  "license": "BSD 3-Clause",
  "private": true,
  "scripts": {
    "lint": "actl lint",
    "commit": "actl commit",
    "typecheck": "actl typecheck",
    "format": "actl format"
  },
  "devDependencies": {
    "@atlantis-lab/actl": "^0.4.27",
    "husky": "^4.3.8",
    "lerna": "3.22.1",
    "typescript": "^4.1.3"
  },
  "husky": {
    "hooks": {
      "pre-commit": "actl precommit",
      "commit-msg": "actl commitmsg"
    }
  },
  "workspaces": [
    "lessons/**/*",
    "practice/**/*"
  ]
}

```
yarn.lock (@atlantis-lab/actl)
```javascript
"@atlantis-lab/actl-build@0.0.19":
  resolved "https://registry.yarnpkg.com/@atlantis-lab/actl-build/-/actl-build-0.0.19.tgz#68535cb9f80b772c0d6470f577cf0890c6ca02a2"
"@atlantis-lab/actl-build@^0.0.8":
  resolved "https://registry.yarnpkg.com/@atlantis-lab/actl-build/-/actl-build-0.0.8.tgz#38fd05fca3bf3680dda3ecf5a95118825501e4f9"
"@atlantis-lab/actl-check@0.4.27":
  resolved "https://registry.yarnpkg.com/@atlantis-lab/actl-check/-/actl-check-0.4.27.tgz#75771008f3bcdb1fb467a725272d54bab2addabf"
"@atlantis-lab/actl-commit@0.0.27":
  resolved "https://registry.yarnpkg.com/@atlantis-lab/actl-commit/-/actl-commit-0.0.27.tgz#39a699b272add36bf35d8ab1eb465667e01ec0a8"
"@atlantis-lab/actl-commitmsg@0.0.27":
  resolved "https://registry.yarnpkg.com/@atlantis-lab/actl-commitmsg/-/actl-commitmsg-0.0.27.tgz#8f81c6beb91d429fcbf49fade23540d1ce4a4abe"
"@atlantis-lab/actl-cr-publisher@0.0.2":
  resolved "https://registry.yarnpkg.com/@atlantis-lab/actl-cr-publisher/-/actl-cr-publisher-0.0.2.tgz#1ea3ef472dc4d918a8dfe75d11e98476e887bc85"
    "@atlantis-lab/actl-build" "^0.0.8"
"@atlantis-lab/actl-format@0.0.3":
  resolved "https://registry.yarnpkg.com/@atlantis-lab/actl-format/-/actl-format-0.0.3.tgz#4d3dbdaf7c2d44b5728bef445b2c37d20eab5dd1"
"@atlantis-lab/actl-lint@0.1.27":
  resolved "https://registry.yarnpkg.com/@atlantis-lab/actl-lint/-/actl-lint-0.1.27.tgz#b66d1a7bf7b562f4739fb22b9af1b96153ec3cf0"
"@atlantis-lab/actl-precommit@0.0.27":
  resolved "https://registry.yarnpkg.com/@atlantis-lab/actl-precommit/-/actl-precommit-0.0.27.tgz#8562220ce75f3a58140520914d3bdcc5890372b9"
"@atlantis-lab/actl-test@0.0.16":
  resolved "https://registry.yarnpkg.com/@atlantis-lab/actl-test/-/actl-test-0.0.16.tgz#9b74761d5b00be2eda448327f196bf684f4a7674"
"@atlantis-lab/actl-typecheck@0.1.27":
  resolved "https://registry.yarnpkg.com/@atlantis-lab/actl-typecheck/-/actl-typecheck-0.1.27.tgz#88e9ea7a211feb3473803e0607f8d98da3ceba4a"
"@atlantis-lab/actl@^0.4.27":
  resolved "https://registry.yarnpkg.com/@atlantis-lab/actl/-/actl-0.4.27.tgz#edf75f5d7f9991f04fb4d635528dbcf474c5c6f4"
    "@atlantis-lab/actl-build" "0.0.19"
    "@atlantis-lab/actl-check" "0.4.27"
    "@atlantis-lab/actl-commit" "0.0.27"
    "@atlantis-lab/actl-commitmsg" "0.0.27"
    "@atlantis-lab/actl-cr-publisher" "0.0.2"
    "@atlantis-lab/actl-format" "0.0.3"
    "@atlantis-lab/actl-lint" "0.1.27"
    "@atlantis-lab/actl-precommit" "0.0.27"
    "@atlantis-lab/actl-test" "0.0.16"
    "@atlantis-lab/actl-typecheck" "0.1.27"

```
yarn.lock (husky)
```
husky@^4.3.8:
  resolved "https://registry.yarnpkg.com/husky/-/husky-4.3.8.tgz#31144060be963fd6850e5cc8f019a1dfe194296d"
```

**Comment by themetronome** [comment]
Попробовал заменить в своём проекте **commitmsg.js** импорт **execa** с `__importDefault(require(...))` на обычный `require()` (как в импорте **@oclif/command**) и commitmsg хук перестал падать с ошибкой при коммите

![Screenshot from 2021-03-11 17-10-31](https://user-images.githubusercontent.com/27724692/110795923-6d8c3380-8288-11eb-8511-7b57efcc054e.png)
![Screenshot from 2021-03-11 17-11-01](https://user-images.githubusercontent.com/27724692/110795941-73821480-8288-11eb-9472-c58cb6d2bd99.png)
